In [185]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math
from  datetime import datetime
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',150)

In [27]:
train_data = pd.read_excel(r"../data/A_data.xlsx")
test_data = pd.read_excel(r"../data/submit.xlsx")

In [28]:
used_cols = ["时间","基站编号","小区编号","小区内的平均用户数","小区PDCP层所发送的下行数据的总吞吐量比特",
"小区PDCP层所接收到的上行数据的总吞吐量比特","平均激活用户数"]

In [29]:
train = train_data[used_cols]

In [30]:
train

时间     基站编号      小区编号  小区内的平均用户数  小区PDCP层所发送的下行数据的总吞吐量比特  \
0      2021-08-28 00:00  1200071  26019014    22.6341             30825953056   
1      2021-08-28 00:00  1200071  26019015    19.1064             14185653168   
2      2021-08-28 00:00  1200071  26019016    15.4729              7767242120   
3      2021-08-28 00:00  1200071  26019023     0.0509                  137312   
4      2021-08-28 00:00  1200071  26019024     0.6355                26593440   
...                 ...      ...       ...        ...                     ...   
40363  2021-09-25 23:00  1200075  26019033     7.0792              1064325632   
40364  2021-09-25 23:00  1200075  26019034     1.3647              1651173776   
40365  2021-09-25 23:00  1200075  26019035     2.4111              2215657728   
40366  2021-09-25 23:00  1200075  26019027    11.7958             22816769808   
40367  2021-09-25 23:00  1200075  26019028    15.4725             12474813456   

       小区PDCP层所接收到的上行数据的总吞吐量比特  平均激活用户数  
0                   1335290712   2.7893  
1                   2829868592   3.9198  
2                   1194709896   3.1944  
3                       205800   0.0004  
4                     12935840   0.0263  
...                        ...      ...  
40363                371490528   0.2405  
40364                 87614416   0.0864  
40365                219697536   0.2187  
40366               1506731744   1.6753  
40367               1764214216   1.7410  

[40368 rows x 7 columns]

In [31]:
train["小区的PDCP流量"] = train["小区PDCP层所发送的下行数据的总吞吐量比特"] + train["小区PDCP层所接收到的上行数据的总吞吐量比特"]
train

时间     基站编号      小区编号  小区内的平均用户数  小区PDCP层所发送的下行数据的总吞吐量比特  \
0      2021-08-28 00:00  1200071  26019014    22.6341             30825953056   
1      2021-08-28 00:00  1200071  26019015    19.1064             14185653168   
2      2021-08-28 00:00  1200071  26019016    15.4729              7767242120   
3      2021-08-28 00:00  1200071  26019023     0.0509                  137312   
4      2021-08-28 00:00  1200071  26019024     0.6355                26593440   
...                 ...      ...       ...        ...                     ...   
40363  2021-09-25 23:00  1200075  26019033     7.0792              1064325632   
40364  2021-09-25 23:00  1200075  26019034     1.3647              1651173776   
40365  2021-09-25 23:00  1200075  26019035     2.4111              2215657728   
40366  2021-09-25 23:00  1200075  26019027    11.7958             22816769808   
40367  2021-09-25 23:00  1200075  26019028    15.4725             12474813456   

       小区PDCP层所接收到的上行数据的总吞吐量比特  平均激活用户数    小区的PDCP流量  
0                   1335290712   2.7893  32161243768  
1                   2829868592   3.9198  17015521760  
2                   1194709896   3.1944   8961952016  
3                       205800   0.0004       343112  
4                     12935840   0.0263     39529280  
...                        ...      ...          ...  
40363                371490528   0.2405   1435816160  
40364                 87614416   0.0864   1738788192  
40365                219697536   0.2187   2435355264  
40366               1506731744   1.6753  24323501552  
40367               1764214216   1.7410  14239027672  

[40368 rows x 8 columns]

In [32]:
train['time']=pd.to_datetime(train['时间'])
train

时间     基站编号      小区编号  小区内的平均用户数  小区PDCP层所发送的下行数据的总吞吐量比特  \
0      2021-08-28 00:00  1200071  26019014    22.6341             30825953056   
1      2021-08-28 00:00  1200071  26019015    19.1064             14185653168   
2      2021-08-28 00:00  1200071  26019016    15.4729              7767242120   
3      2021-08-28 00:00  1200071  26019023     0.0509                  137312   
4      2021-08-28 00:00  1200071  26019024     0.6355                26593440   
...                 ...      ...       ...        ...                     ...   
40363  2021-09-25 23:00  1200075  26019033     7.0792              1064325632   
40364  2021-09-25 23:00  1200075  26019034     1.3647              1651173776   
40365  2021-09-25 23:00  1200075  26019035     2.4111              2215657728   
40366  2021-09-25 23:00  1200075  26019027    11.7958             22816769808   
40367  2021-09-25 23:00  1200075  26019028    15.4725             12474813456   

       小区PDCP层所接收到的上行数据的总吞吐量比特  平均激活用户数    小区的PDCP流量                time  
0                   1335290712   2.7893  32161243768 2021-08-28 00:00:00  
1                   2829868592   3.9198  17015521760 2021-08-28 00:00:00  
2                   1194709896   3.1944   8961952016 2021-08-28 00:00:00  
3                       205800   0.0004       343112 2021-08-28 00:00:00  
4                     12935840   0.0263     39529280 2021-08-28 00:00:00  
...                        ...      ...          ...                 ...  
40363                371490528   0.2405   1435816160 2021-09-25 23:00:00  
40364                 87614416   0.0864   1738788192 2021-09-25 23:00:00  
40365                219697536   0.2187   2435355264 2021-09-25 23:00:00  
40366               1506731744   1.6753  24323501552 2021-09-25 23:00:00  
40367               1764214216   1.7410  14239027672 2021-09-25 23:00:00  

[40368 rows x 9 columns]

In [102]:
def get_time_window(series_data, period):
    pre_data = series_data.values
    x_train = np.zeros((len(pre_data)-period+1, period))
    y_train = pre_data[period-1:]

    for i in range(0,len(pre_data)-period+1):
        x_train[i,:] = pre_data[i:i+8]

    return x_train, y_train

In [117]:
#SS算法
def calculate_SS_condition(post_point, pre_point,threshold):
    
    if abs(post_point - pre_point) > threshold:
        return 1
    else:
        return 0


In [118]:
def get_dynamic_threhold(pre_time_lines):
    return min(np.max(pre_time_lines) - np.average(pre_time_lines), np.average(pre_time_lines) - np.min(pre_time_lines))

In [122]:
def SS(time_lines, count_threhold = 6):
    outlines = []
    for i in range(len(time_lines)):
        count = 0
        target_point = time_lines[i,-1]

        threshold = get_dynamic_threhold(time_lines[i, :-1])
        
        for j in range(len(time_lines[0])- 1):
            count += calculate_SS_condition(target_point, time_lines[i, j], threshold=threshold)

        if count > count_threhold:
            outlines.append(1)
        else:
            outlines.append(0)
    return outlines

In [174]:
#LS算法
def LS(time_lines):
    outpoints = []
    for i in range(len(time_lines)):
        line = time_lines[i, :-1]
        check_point = time_lines[i, -1]
        line_mean = np.mean(line)
        
        line_std = np.std(line)
        if abs(check_point - line_mean) > (3 * line_std):
            outpoints.append(1)
        else:
            outpoints.append(0)

    return outpoints

In [107]:
#chain同比算法
def chain(time_lines, max_threshold, min_threshold):
    outpoints = []
    for i in range(len(time_lines)):
        line = time_lines[i,:-1]
        check_point = time_lines[i, -1]
        period_max = np.max(line) * max_threshold
        period_min = np.min(line) * min_threshold
        if (check_point > period_max or check_point <period_min):
            outpoints.append(1)

        else:
            outpoints.append(0)
    return outpoints

In [108]:
#CA同比振幅算法
def CA(time_lines, threshold):
    outpoints = []
    for i in range(len(time_lines)):
        line = time_lines[i,:]
        #check_point = time_lines[i, -1]
        amplitudes = []
        for i in range(len(line)-1):
            amp = abs((line[i+1] - line[i]) / line[i])
            amplitudes.append(amp)
        if amplitudes[-1] > max(amplitudes[:-1]) * threshold:
            outpoints.append(1)
        else:
            outpoints.append(0)
    return outpoints


In [175]:
def my_AD_method(data_series, period, ss_count_thre, chain_max_thre, chain_min_thre, ca_amp_thre):
    
    #先从每个小区总时序中获得时间窗
    x, y = get_time_window(data_series,period=period)
    #计算SS
    ss_out = SS(x, ss_count_thre)
    #计算LS
    ls_out = LS(x)
    #计算chain
    chain_out = chain(x,chain_max_thre,chain_min_thre)
    #计算ca
    ca_out = CA(x, ca_amp_thre)

    ss_out = np.array(ss_out)
    ls_out = np.array(ls_out)
    chain_out = np.array(chain_out)
    ca_out = np.array(ca_out)

    oddity_index = np.zeros(len(ss_out))

    last_out = ss_out + ls_out + chain_out + ca_out
    
    oddity_sum = sum(last_out >= 3)
    oddity_index[last_out >= 3] = 1
    
    return oddity_sum, oddity_index

In [110]:
community_id = train["小区编号"].unique()
community_id

array([26019014, 26019015, 26019016, 26019023, 26019024, 26019010,
       26019011, 26019012, 26019013, 26019057, 26019058, 26019009,
       26019007, 26019008, 26019030, 26019031, 26019032, 26019004,
       26019005, 26019006, 26019021, 26019022, 26019020, 26019025,
       26019017, 26019018, 26019019, 26019043, 26019044, 26019040,
       26019041, 26019042, 26019001, 26019002, 26019003, 26019037,
       26019038, 26019039, 26019046, 26019047, 26019048, 26019054,
       26019055, 26019056, 26019051, 26019052, 26019053, 26019036,
       26019045, 26019049, 26019050, 26019029, 26019026, 26019033,
       26019034, 26019035, 26019027, 26019028], dtype=int64)

In [111]:
len(community_id)

58

In [269]:
#求所有小区的异常点
#先建立所有小区输出结果的存储空间：

ad_col = "小区的PDCP流量"  #需要异常检测(Anomaly detection)的指标
target_length = len(train[train["小区编号"] == 26019014][ad_col])  #取第一个小区计算指标的总时间序列长度
period = 8 #分割时间窗的长度（用于计算的时间序列的长度）

mean_users_oddity_sum = []   #保存每个小区异常点的总数
mean_users_oddity_index = np.zeros((len(community_id), (target_length-period+1))) #保存每个小区异常点的索引（相对索引，相对于每个小区而言）

for i in range(len(community_id)):
    data_series = train[train["小区编号"] == community_id[i]][ad_col] #注意跑别的指标的时候，检查此处是否修改
    odd_sum, oddity_index = my_AD_method(data_series=data_series, period=8, ss_count_thre=6, chain_max_thre=3, chain_min_thre=0.33, ca_amp_thre=3)
        
    mean_users_oddity_sum.append(odd_sum)
    mean_users_oddity_index[i,:] = oddity_index

In [270]:
sum(mean_users_oddity_sum)

1204

In [181]:
sum(np.sum(mean_users_oddity_index,0)>10)

23

In [190]:
station_id = train["基站编号"].unique()
station_id

array([1200071, 1200072, 1200074, 1200073, 1200075], dtype=int64)

In [212]:
train[train["基站编号"] == station_id[0]]["小区编号"].unique()

array([26019001, 26019002, 26019003, 26019037, 26019038, 26019039,
       26019046, 26019047, 26019048, 26019054, 26019055, 26019056,
       26019051, 26019052, 26019053, 26019036, 26019045], dtype=int64)

In [279]:
check_now = np.sum(mean_users_oddity_index[49:], 0)
sum(check_now>4)

1

In [275]:
last_sum = mean_users_oddity_sum.copy()
last_p = mean_users_oddity_index.copy()
np.sum(last_p)

1204.0

In [280]:
for row in last_p[49:]:
    row[check_now>4] = 0
np.sum(last_p)

1185.0

In [230]:
def get_lastout_window(series_data, period):
    pre_data = series_data
    x_train = np.zeros((len(pre_data)-period+1, period))
    y_train = pre_data[period-1:]

    for i in range(0,len(pre_data)-period+1):
        x_train[i,:] = pre_data[i:i+8]

    return x_train, y_train

In [245]:
np.sum(last_p)

998.0

In [281]:
np.savetxt(r"../data/target3_label.txt",last_p)

In [284]:
ad_cycle = 0
for line in last_p:
    op, po = get_lastout_window(line, 8)
    ad_cycle += sum(np.sum(op,1)>2)

ad_cycle
    

182

In [239]:
sum(np.sum(op,1)>1)

0

In [186]:
train.groupby("基站编号")["小区编号"].unique()

基站编号
1200071    [26019014, 26019015, 26019016, 26019023, 26019...
1200072    [26019007, 26019008, 26019030, 26019031, 26019...
1200073    [26019001, 26019002, 26019003, 26019037, 26019...
1200074    [26019017, 26019018, 26019019, 26019043, 26019...
1200075    [26019049, 26019050, 26019029, 26019026, 26019...
Name: 小区编号, dtype: object